(function () {
  window.publishGeneratedSite = async function (options) {
    var token = options.token;
    var repoName = options.repoName;
    var generatedSite = options.generatedSite;

    var user = await github("/user", token);
    var repo;
    try {
      repo = await github("/user/repos", token, {
        method: "POST",
        body: { name: repoName, description: "Static site generated by Docs2Site", private: false, auto_init: true, has_issues: false, has_projects: false, has_wiki: false }
      });
    } catch (error) {
      if (error.status === 422) throw new Error("כבר קיים repository בשם הזה. בחרו שם אחר.");
      throw error;
    }

    await delay(1200);
    var headRef = await github("/repos/" + user.login + "/" + repoName + "/git/ref/heads/main", token);
    var headCommit = await github("/repos/" + user.login + "/" + repoName + "/git/commits/" + headRef.object.sha, token);

    var blobs = await Promise.all(generatedSite.files.map(function (file) {
      return github("/repos/" + user.login + "/" + repoName + "/git/blobs", token, {
        method: "POST",
        body: { content: file.content, encoding: "utf-8" }
      }).then(function (blob) {
        return { path: file.path, mode: "100644", type: "blob", sha: blob.sha };
      });
    }));

    var tree = await github("/repos/" + user.login + "/" + repoName + "/git/trees", token, {
      method: "POST",
      body: { base_tree: headCommit.tree.sha, tree: blobs }
    });
    var commit = await github("/repos/" + user.login + "/" + repoName + "/git/commits", token, {
      method: "POST",
      body: { message: "Publish site generated by Docs2Site", tree: tree.sha, parents: [headRef.object.sha] }
    });
    await github("/repos/" + user.login + "/" + repoName + "/git/refs/heads/main", token, {
      method: "PATCH",
      body: { sha: commit.sha, force: false }
    });
    await delay(1200);
    await github("/repos/" + user.login + "/" + repoName + "/pages", token, {
      method: "POST",
      body: { build_type: "legacy", source: { branch: "main", path: "/" } }
    });

    return {
      repositoryUrl: repo.html_url,
      siteUrl: "https://" + user.login.toLowerCase() + ".github.io/" + repoName + "/"
    };
  };

  function delay(milliseconds) {
    return new Promise(function (resolve) { setTimeout(resolve, milliseconds); });
  }

  async function github(path, token, options) {
    options = options || {};
    var response = await fetch("https://api.github.com" + path, {
      method: options.method || "GET",
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: "Bearer " + token,
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json"
      },
      body: options.body ? JSON.stringify(options.body) : undefined
    });
    var data = await response.json().catch(function () { return {}; });
    if (!response.ok) {
      var error = new Error(data.message || "GitHub החזיר שגיאה.");
      error.status = response.status;
      throw error;
    }
    return data;
  }
})();